[package]
name = "color"
version = "0.1.0"
authors = ["nathanfaucett <nathanfaucett@gmail.com>"]

[dependencies.num]
git = "https://github.com/nathanfaucett/rs-num.git"

[dependencies]
regex = "0.1.8"
